### ISSUE TITLE
Dice results larger than 4 digits

### ISSUE THREAD

**Issue by Boogen222** [valentine195/obsidian-dice-roller#88]
Sorry if this has already been address, but dice results larger than 4 digits give back an NaN result. The formula is still available if you hover over them.

![image](https://user-images.githubusercontent.com/103544918/163077985-cb8fda30-87b6-4822-84c4-1a2b6112f7b4.png)

![image](https://user-images.githubusercontent.com/103544918/163078007-0b60341e-303d-4e87-930c-2f93ce080cf3.png)

**Comment by JYCasalis** [comment]
I tried to fix the described issue, not 100% confident since this is my first time trying to contribute / create a pull request :-)

@boogen222, until this is fixed, you can just change the Round results setting (from plugin settings) to anything else than None. You wont have the NaN anymore but all dice formula result will always be displayed as an integer (Round result None is to display dice formula result as a float with two decimals).
